env:
  browser: true
  es6: true
  node: true
extends:
  - airbnb-base
  - plugin:@typescript-eslint/recommended
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
  project:
    - ./tsconfig.json
plugins:
  - '@typescript-eslint'
settings:
  import/resolver:
    node:
      extensions:
      - ".js"
      - ".jsx"
      - ".ts"
      - ".tsx"
rules:
  'no-param-reassign': 0
  '@typescript-eslint/no-explicit-any': 0
